create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  name text not null, phone text not null, email text not null default '',
  reservation_date date not null, reservation_time time not null,
  guests text not null, note text not null default '',
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled','completed')),
  created_at timestamptz not null default now()
);
create index if not exists reservations_schedule_idx on public.reservations (reservation_date, reservation_time);
alter table public.reservations enable row level security;
